label: ["diffusion_ard", "random", "local_search", "bfs", "dfs"]
save_dir: ./logs/Grid/
n_exp: 10 # number of experiments with different random seeds
bo_settings:
  batch_size: 1 # batch size
  max_iters: 300 # number of total queries
  max_radius: 10 # the maximum hop distance to the centre node when constructing the local context graph
  n_init: 30 # Initial queried points 
  Q: 4000 # the size of the context ComboSubgraph
  large_Q: False
  exploitation: False
  start_location: random 
  restart_location: queried_best #[same_as_start, queried_best]
  tr_settings:    # settings related to the trust region on the graph search space
    n_nodes_min: 10         # the min number of nodes in the trust region
    trust_region_multiplier: 1.5 
    succ_tol: 10       # success tolerance
    fail_tol: 30      # fail tolerance
problem_name: synthetic # the experimental problem type
problem_settings:  
  n: 5000 # number of nodes in the underlying (synthetic) random graphs
  k: 4 # number of combinations
  graph_type: grid 
  underlying_function: ackley 
  noise: 0.5
